# Generated by Django 5.1.7 on 2025-03-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('ctc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rollno', models.BigIntegerField(unique=True)),
                ('batch', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField()),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsapi.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsapi.student')),
            ],
        ),
    ]
